$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  genome_paths:
    type: string
  hmms_to_align:
    type: string
    description: path to .hmm file containing all genes you want in the tree concatenated
  tree_params:
    type: object
      properties:
        outgroup:
          type: string
          description: genome_id of outgroup, or comma separated genome_ids (must be monophyletic)
        model:
          type: string
          description: https://github.com/amkozlov/raxml-ng/wiki/Input-data#evolutionary-model